[package]
name = "sudoku-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1"
actix-web = "4"
actix-files = "0.6.2"
lazy_static = "1.4.0"
actix-rt = "2.10.0"
fastrand = "2.1.0"

[dev-dependencies]
cargo-tarpaulin = "0.30.0"
codspeed-criterion-compat = "2.6.0"
criterion = "0.5.1"

[lib]
name = "sudoku_rust"
path = "src/main.rs"

[profile.release]
lto = true
opt-level = 3

[profile.dev]
opt-level = "s"

[[bench]]
name = "sudoku_benchmarks"
harness = false
